name: Build job
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Debug, Release, Profile Debug, Profile Release]
    name: ${{ runner.os }}), ${{ matrix.configuration }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302
      - name: Build
        run: dotnet build -c "${{ matrix.configuration }}"
      - name: Test
        run: dotnet test -c "${{ matrix.configuration }}"
