name: Build job
on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Debug, Release, Profile Debug, Profile Release]
      fail-fast: false
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Publish
        run: dotnet publish -c "${{ matrix.configuration }}"
      - name: Test
        run: dotnet test -c "${{ matrix.configuration }}"
      - if: matrix.configuration == 'Release' && matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.configuration }}
          path: Ryujinx/bin/${{ matrix.configuration }}/netcoreapp3.1
          if-no-files-found: error
